[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
airdrop = "HMYF4pnR6PDcLYibwYcjmDYkCrvvmPb8vnzTuejUErzR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/lightning/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
